# Generated by Django 4.0.1 on 2022-03-16 09:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SredModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('memo', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 3, 16, 9, 23, 54, 641336, tzinfo=utc), verbose_name='掲示板作成日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='編集日時')),
                ('delete_flg', models.BooleanField(default=False, help_text='削除されたらTrue', verbose_name='掲示板削除フラグ')),
            ],
        ),
        migrations.CreateModel(
            name='Sred_msg_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_detail', models.CharField(max_length=255, verbose_name='メッセージ内容')),
                ('msg_author', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2022, 3, 16, 9, 23, 54, 641336, tzinfo=utc), verbose_name='メッセージ送信日時')),
                ('delete_flg', models.BooleanField(default=False, help_text='削除されたらTrue', verbose_name='メッセージ削除フラグ')),
                ('sred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.sredmodel')),
            ],
        ),
    ]
